#!/usr/bin/env node

/**
 * BIND AI Pack — Redash MCP Server
 *
 * 리대시 API를 통해 Athena/MySQL에 SQL 쿼리를 실행하고 결과를 반환.
 * 비개발자가 자연어로 데이터를 조회할 수 있도록 AI가 SQL을 생성해서 실행.
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

const REDASH_URL = process.env.REDASH_URL || 'http://52.79.76.239';
const REDASH_API_KEY = process.env.REDASH_API_KEY;

if (!REDASH_API_KEY) {
  console.error('REDASH_API_KEY 환경변수가 필요합니다.');
  process.exit(1);
}

const headers = {
  Authorization: `Key ${REDASH_API_KEY}`,
  'Content-Type': 'application/json',
};

// --- Redash API 헬퍼 ---

async function fetchJson(path, options = {}) {
  const res = await fetch(`${REDASH_URL}/api${path}`, {
    ...options,
    headers: { ...headers, ...options.headers },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Redash API ${res.status}: ${text}`);
  }
  return res.json();
}

async function listDataSources() {
  return fetchJson('/data_sources');
}

async function getSchema(dataSourceId) {
  return fetchJson(`/data_sources/${dataSourceId}/schema`);
}

async function listSavedQueries(page = 1, pageSize = 25) {
  return fetchJson(`/queries?page=${page}&page_size=${pageSize}`);
}

async function executeQuery(dataSourceId, sql) {
  // 1. 쿼리 생성
  const query = await fetchJson('/queries', {
    method: 'POST',
    body: JSON.stringify({
      data_source_id: dataSourceId,
      query: sql,
      name: `bind-ai-${Date.now()}`,
      description: 'Auto-generated by BIND AI Pack',
    }),
  });

  // 2. 실행 요청
  const job = await fetchJson(`/queries/${query.id}/results`, {
    method: 'POST',
    body: JSON.stringify({}),
  });

  // 3. 결과 대기 (polling)
  let result = job;
  let attempts = 0;
  const maxAttempts = 60; // 최대 60초 대기

  while (result.job && attempts < maxAttempts) {
    await new Promise((r) => setTimeout(r, 1000));
    result = await fetchJson(`/jobs/${result.job.id}`);
    attempts++;
  }

  if (result.job && result.job.status !== 3) {
    // 완료 후 쿼리 정리
    await cleanupQuery(query.id);
    throw new Error(`쿼리 실행 타임아웃 (${maxAttempts}초)`);
  }

  // 4. 결과 조회
  const queryResult = await fetchJson(`/queries/${query.id}/results`);

  // 5. 임시 쿼리 삭제 (정리)
  await cleanupQuery(query.id);

  return queryResult.query_result?.data || queryResult;
}

async function cleanupQuery(queryId) {
  try {
    await fetch(`${REDASH_URL}/api/queries/${queryId}`, {
      method: 'DELETE',
      headers,
    });
  } catch {
    // 삭제 실패해도 무시
  }
}

async function runSavedQuery(queryId, parameters = {}) {
  const result = await fetchJson(`/queries/${queryId}/results`, {
    method: 'POST',
    body: JSON.stringify({ parameters }),
  });

  // polling
  let data = result;
  let attempts = 0;
  while (data.job && attempts < 60) {
    await new Promise((r) => setTimeout(r, 1000));
    data = await fetchJson(`/jobs/${data.job.id}`);
    attempts++;
  }

  const final = await fetchJson(`/queries/${queryId}/results`);
  return final.query_result?.data || final;
}

// --- 결과 포맷팅 ---

function formatResult(data) {
  if (!data || !data.rows) return '결과 없음';

  const columns = data.columns?.map((c) => c.name) || [];
  const rows = data.rows || [];

  if (rows.length === 0) return '결과: 0건';

  // 최대 100행까지만 표시
  const displayRows = rows.slice(0, 100);
  const truncated = rows.length > 100 ? `\n\n... 외 ${rows.length - 100}건 (총 ${rows.length}건)` : '';

  // 마크다운 테이블
  let table = '| ' + columns.join(' | ') + ' |\n';
  table += '| ' + columns.map(() => '---').join(' | ') + ' |\n';
  for (const row of displayRows) {
    table += '| ' + columns.map((c) => String(row[c] ?? '')).join(' | ') + ' |\n';
  }

  return `${rows.length}건 조회됨\n\n${table}${truncated}`;
}

// --- MCP 서버 ---

const server = new Server(
  { name: 'bind-redash', version: '0.1.0' },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: 'list_data_sources',
      description: '리대시에 등록된 데이터소스(DB) 목록을 조회합니다. 쿼리를 실행하기 전에 어떤 데이터소스가 있는지 확인하세요.',
      inputSchema: { type: 'object', properties: {} },
    },
    {
      name: 'get_schema',
      description: '특정 데이터소스의 테이블/컬럼 스키마를 조회합니다. SQL 작성 전에 테이블 구조를 확인하세요.',
      inputSchema: {
        type: 'object',
        properties: {
          data_source_id: { type: 'number', description: '데이터소스 ID (list_data_sources로 확인)' },
        },
        required: ['data_source_id'],
      },
    },
    {
      name: 'execute_sql',
      description: '리대시를 통해 SQL 쿼리를 실행합니다. SELECT만 허용. 반드시 LIMIT을 포함하세요 (최대 1000).',
      inputSchema: {
        type: 'object',
        properties: {
          data_source_id: { type: 'number', description: '데이터소스 ID' },
          sql: { type: 'string', description: 'SELECT SQL 쿼리 (LIMIT 필수)' },
        },
        required: ['data_source_id', 'sql'],
      },
    },
    {
      name: 'list_saved_queries',
      description: '리대시에 저장된 쿼리 목록을 조회합니다.',
      inputSchema: {
        type: 'object',
        properties: {
          page: { type: 'number', description: '페이지 번호 (기본 1)', default: 1 },
        },
      },
    },
    {
      name: 'run_saved_query',
      description: '리대시에 이미 저장된 쿼리를 실행합니다. 파라미터가 있으면 전달할 수 있습니다.',
      inputSchema: {
        type: 'object',
        properties: {
          query_id: { type: 'number', description: '쿼리 ID' },
          parameters: { type: 'object', description: '쿼리 파라미터 (key-value)', default: {} },
        },
        required: ['query_id'],
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
      case 'list_data_sources': {
        const sources = await listDataSources();
        const formatted = sources.map((s) => `- [${s.id}] ${s.name} (${s.type})`).join('\n');
        return { content: [{ type: 'text', text: `데이터소스 목록:\n${formatted}` }] };
      }

      case 'get_schema': {
        const schema = await getSchema(args.data_source_id);
        const tables = (schema.schema || schema)
          .map((t) => `### ${t.name}\n${t.columns.join(', ')}`)
          .join('\n\n');
        return { content: [{ type: 'text', text: tables }] };
      }

      case 'execute_sql': {
        const sql = args.sql.trim();

        // SELECT만 허용
        if (!/^SELECT/i.test(sql)) {
          return { content: [{ type: 'text', text: '오류: SELECT 쿼리만 실행할 수 있습니다.' }] };
        }

        // LIMIT 강제
        if (!/LIMIT\s+\d+/i.test(sql)) {
          return { content: [{ type: 'text', text: '오류: LIMIT 절을 포함해주세요 (최대 1000).' }] };
        }

        const data = await executeQuery(args.data_source_id, sql);
        return { content: [{ type: 'text', text: formatResult(data) }] };
      }

      case 'list_saved_queries': {
        const result = await listSavedQueries(args.page || 1);
        const queries = result.results || result;
        const formatted = queries
          .map((q) => `- [${q.id}] ${q.name} (데이터소스: ${q.data_source_id})`)
          .join('\n');
        return { content: [{ type: 'text', text: `저장된 쿼리:\n${formatted}` }] };
      }

      case 'run_saved_query': {
        const data = await runSavedQuery(args.query_id, args.parameters || {});
        return { content: [{ type: 'text', text: formatResult(data) }] };
      }

      default:
        return { content: [{ type: 'text', text: `알 수 없는 도구: ${name}` }] };
    }
  } catch (err) {
    return { content: [{ type: 'text', text: `오류: ${err.message}` }] };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
